name: Andoird CI/CD
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build with gradle
        run: ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: App
          path: app/build/outputs/apk/debug/app-debug.app
